server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: roadmap-backend

  datasource:
    url: jdbc:h2:mem:roadmapdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: your-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.roadmap: DEBUG
    org.springframework.security: DEBUG
